### ISSUE TITLE
Allow users to tag request and offers

### ISSUE THREAD

**Issue by neopostmodern** [caTUstrophy/frontend#59]
There is a suitable [component](http://www.material-ui.com/#/components/chip) for this which allows deletion out of the box. A HOC should be created.

**Comment by numbleroot** [comment]
On backend side we envisioned the following: Before displaying the page for creating an offer or a request, the list of all tags available in the system was retrieved (probably `GET /tags`). Via a nice graphical visualization the user is able to select the matching tags from all available tags. Via this mechanism, no invalid or non-existant tag should make it through to backend side (though we will certainly check for that).

**Comment by numbleroot** [comment]
Alright, `GET /tags` is now existing in backend. Find it here: [List all tags documentation](https://github.com/caTUstrophy/backend#list-all-tags).
