### ISSUE TITLE
User registration: add mobile phone and consent to share phone and mail on matching

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/frontend#63]
When a user is registering for our service, we need to additionally ask for mobile phone number and have a mandatory check box stating that with registering in our service the user is consenting to have mobile phone number and mail address shared with the other user in case of a match.

**Comment by neopostmodern** [comment]
Is (mobile) phone number mandatory?
Bonus points for allowing multiple phone numbers? (Because operators)

**Comment by numbleroot** [comment]
No, mandatory is probably too hard, might be that a user does not possess a mobile phone.

Multiple phone numbers is a good idea. Please send the phone numbers a user sent as an array. That array might contain zero, one or multiple numbers. I would also rather not put any strict validity checks on those numbers as we do not know what specific format those numbers will have. This is information that is only send to matched users anyway, so we do not need to process the supplied numbers.

Please see [Create user](https://github.com/caTUstrophy/backend#create-user-registration), I adapted the documentation.
