### ISSUE TITLE
Check if all backend endpoints have a corresponding frontend interface

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/frontend#75]
For complete functionality, please verify that each exposed endpoint available at backend side is addressable via an interface on frontend side.

**Comment by jeichelbaum** [comment]
UPDATE /matching/:matchingID

**Comment by jeichelbaum** [comment]
GET /regions/:regionID/matchings

**Comment by jeichelbaum** [comment]
???? UPDATE /me

**Comment by tomlord90** [comment]
First two are done. Clemens is taking a look at the UPDATE /me issue
