### ISSUE TITLE
Check frontend flow consistency

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/frontend#76]
Please verify that all "flows" through the frontend make sense, are bug free and redirect to correct next URLs (e.g. on logout).

**Comment by jeichelbaum** [comment]
no feedback or redirect after adding user to region /regions/:regionID/admins

**Comment by jeichelbaum** [comment]
other than that, the whole flow is pretty consistent

**Comment by tomlord90** [comment]
Redirect added on successful admin promotion at /regions/:regionID/admins
