### ISSUE TITLE
Visualize matching score and global optimum marker

### ISSUE THREAD

**Issue by numbleroot** [caTUstrophy/frontend#78]
When ready on backend side: Update the display of offers and requests suitable for a matching to a request or an offer to visualize the matching scores and the `global optimum` marked element. The region admin is supposed to be supported in her or his match making decision by these matching scores ranging from 0 - 100. Also one element will by marked as the `global optimum` that - if chosen - should guarantee the region admin to a certain extend that no request should be unmatchable with an offer or vice versa.

See [backend#99](https://github.com/caTUstrophy/backend/issues/99).

**Comment by jeichelbaum** [comment]
backend endpoints
/regions/:regionID/requests/:requestID/recommendations
/regions/:regionID/offers/:offerID/recommendations

response:
var fieldsRecommendations = map[string]interface{}{
	"Region":        fieldsRegion,
	"Request":       fieldsRequest,
	"Offer":         fieldsOffer,
	"MatchingScore": "MatchingScore",
	"Recommended":   "Recommended",
}

**Comment by jeichelbaum** [comment]
there should be only one recommended element among response, might not have highest matchingscore as far as my understanding goes, but should lead to a global optimal matching
